services:
  - type: web
    name: tiktok-ai-analyzer
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
